//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HarvestDatabaseEntities : DbContext
    {
        public HarvestDatabaseEntities()
            : base("name=HarvestDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IngredientCategory> IngredientCategory { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<LastLaunched> LastLaunched { get; set; }
        public virtual DbSet<MealHistory> MealHistory { get; set; }
        public virtual DbSet<MealTime> MealTime { get; set; }
        public virtual DbSet<Metric> Metric { get; set; }
        public virtual DbSet<PlannedMeals> PlannedMeals { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<RecipeClass> RecipeClass { get; set; }
        public virtual DbSet<RecipeIngredient> RecipeIngredient { get; set; }
    }
}
