//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Recipe_Inventory = new HashSet<Recipe_Inventory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeID { get; set; }
        public double Amount { get; set; }
        public Nullable<int> MetricID { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        public virtual Metric Metric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe_Inventory> Recipe_Inventory { get; set; }
    }
}
