//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Inventory
    {
        public int RecipeID { get; set; }
        public int InventoryID { get; set; }
        public double Amount { get; set; }
        public int MetricID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Metric Metric { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
