//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Adapters.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class HarvestDatabaseEntities : DbContext
    {
        public HarvestDatabaseEntities()
            : base("name=HarvestDatabaseEntities")
        {
            IngredientCategory = Set<IngredientCategory>();
            Inventory = Set<Inventory>();
            LastLaunched = Set<LastLaunched>();
            MealHistory = Set<MealHistory>();
            MealTime = Set<MealTime>();
            Metric = Set<Metric>();
            PlannedMeals = Set<PlannedMeals>();
            Recipe = Set<Recipe>();
            RecipeClass = Set<RecipeClass>();
            RecipeIngredient = Set<RecipeIngredient>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<IngredientCategory> IngredientCategory { get; set; }
        internal virtual DbSet<Inventory> Inventory { get; set; }
        internal virtual DbSet<LastLaunched> LastLaunched { get; set; }
        internal virtual DbSet<MealHistory> MealHistory { get; set; }
        internal virtual DbSet<MealTime> MealTime { get; set; }
        internal virtual DbSet<Metric> Metric { get; set; }
        internal virtual DbSet<PlannedMeals> PlannedMeals { get; set; }
        internal virtual DbSet<Recipe> Recipe { get; set; }
        internal virtual DbSet<RecipeClass> RecipeClass { get; set; }
        internal virtual DbSet<RecipeIngredient> RecipeIngredient { get; set; }
    }
}
