//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Adapters.Database
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.RecipeIngredient = new HashSet<RecipeIngredient>();
        }
    
        public int InventoryID { get; set; }
        public string IngredientName { get; set; }
        public string Category { get; set; }
        public double Amount { get; set; }
        public string Measurement { get; set; }
    
        internal virtual IngredientCategory IngredientCategory { get; set; }
        internal virtual Metric Metric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<RecipeIngredient> RecipeIngredient { get; set; }
    }
}
